config/routes.rb
Rails.application.routes.draw do
  root to: 'checkouts#show'

  resources :products
  resource :checkout, only: [:show, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checkout.rb
# Checkout class that can scan items (Product) and apply certain
# promotional campaigns to give discounts.
#
# @example:
#
# pizza = Product.find_by(name: 'Pizza')
#
# co = Checkout.new(DiscountRules::PizzaCombo.new)
# co.scan(pizza)
# co.scan(pizza)
# co.total
#
# => 7.98
class Checkout
  attr_reader :discount_rules

  def initialize(discount_rules)
    @discount_rules = Array(discount_rules)
    @original_products = []
  end

  def scan(product)
    @original_products << product
  end

  def total
    apply_discounts.first
  end

  def products
    apply_discounts.last
  end

  private

  # Internal: Iterate over all discount rules
  # applying each discount and storing the resulting total amount
  # and list of products with new prices.
  # 
  # @returns a tuple containing two itens,
  # the new total amount and the list of products.
  # 
  # @example:
  # 
  # => [7.98, [<Product name: 'Pizza' price: 3.99>, <Product name: 'Pizza' price: 3.99>]]
  def apply_discounts
    total_without_discount = @original_products.map(&:price).reduce(0, :+)

    discount_rules.reduce([total_without_discount, @original_products]) do |(total, products), rule|
      rule.run(total, products)
    end
  end
end

app/models/discount_rules/discount_over_limit.rb
# General dicount rule applied to any kind of product.
# 
# It can be configured with a DISCOUNT percentage that will
# be applied over the total amount if this amount is greater
# than a given LIMIT.
# 
# @returns a tuple containing two itens,
# the new total amount and the list of products.

# @example:
# 
# products = [
#   <Product price: 10.0>,
#   <Product price: 40.0>
# ]
# 
# rule = DiscountRules::DiscountOverLimit.new(30.0, 0.1)
# rule.run(50, products)
# 
# => [45.0, [<Product price: 10.0>, <Product price: 10.0>]]
module DiscountRules
  class DiscountOverLimit
    attr_reader :limit, :discount

    def initialize(limit, discount)
      @limit = limit
      @discount = discount
    end

    def run(total, products)
      new_total = if total > limit
        total * (1 - discount)
      else
        total
      end

      [new_total, products]
    end
  end
end

app/models/discount_rules/pizza_combo.rb
# Discount applied just for pizzas.
# 
# If there are 2 or more pizzas, the price of each pizza
# is fixed in 3.99
# 
# @returns a tuple containing two itens,
# the new total amount and the list of products.
# 
# @example:
# 
# products = [
#   <Product name: 'Pizza' price: 5.99>,
#   <Product name: 'Pizza' price: 5.99>
# ]
# 
# rule = DiscountRules::PizzaCombo.new
# rule.run(11.98, products)
# 
# => [7.98, [<Product name: 'Pizza' price: 3.99>, <Product name: 'Pizza' price: 3.99>]]
module DiscountRules
  class PizzaCombo
    MIN_PIZZAS = 2
    NEW_PRICE = 3.99

    def run(total, products)
      if products.count{ |p| pizza?(p) } >= MIN_PIZZAS
        products.each do |product|
          product.price = NEW_PRICE if pizza?(product)
        end

        total = products.map(&:price).reduce(:+)
      end

      [total, products]
    end

    private

    def pizza?(product)
      !!product.name[/pizza/i]
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :code, uniqueness: true

  before_validation :set_code

  def set_code
    self.code ||= Product.order(:code).last&.code.to_i.next
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  helper_method :available_products, :checkout

  def show
  end

  def update
    render :show
  end

  private

  def checkout
    return @checkout if @checkout.present?

    @checkout = Checkout.new(enabled_discount_rules)
    selected_product_ids.map do |product_id|
      product = Product.find(product_id)
      @checkout.scan(product)
    end

    @checkout
  end

  def available_products
    @available_products ||= Product.all
  end

  def selected_product_ids
    Array(params[:product_ids])
  end

  def enabled_discount_rules
    [
      DiscountRules::PizzaCombo.new,
      DiscountRules::DiscountOverLimit.new(30, 0.1)
    ]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(permitted_params)

    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def destroy
    Product.find(params[:id]).destroy
    redirect_to products_path
  end

  private

  def permitted_params
    params.require(:product).permit(:name, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/checkouts/show.html.erb
<%= form_tag checkout_path, method: 'put', class: 'checkout__form' do %>
  <div class="mdl-layout__content mdl-grid">
    <div class="checkout__summary mdl-card mdl-cell--4-col">
      <h3 class="mdl-layout__title">Summary</h3>
      <div class="checkout_summary_card mdl-card">
        <div class="mdl-card__title mdl-card--expand">
          <h3 id="checkout__grand_total"><%= number_to_currency checkout.total, unit: '‎€' %></h3>
        </div>
        <div class="mdl-card__actions mdl-card--border">
          <a class="checkout__submit mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
            Checkout
          </a>
          <div class="mdl-layout-spacer"></div>
          <i class="material-icons">check</i>
        </div>
      </div>
    </div>

    <div class="checkout_products_list mdl-card mdl-cell--4-col">
      <h3 class="mdl-layout__title centered-content">Available</h3>
      <table class="mdl-data-table mdl-js-data-table" id="products_table">
        <thead>
          <tr>
            <th class="mdl-data-table__cell--non-numeric">Code</th>
            <th class="mdl-data-table__cell--non-numeric">Name</th>
            <th class="mdl-data-table__cell--non-numeric">Price</th>
            <th class="mdl-data-table__cell--non-numeric"></th>
          </tr>
        </thead>
        <tbody>
          <% available_products.each do |product| %>
            <tr>
              <td class="mdl-data-table__cell--non-numeric"><%= "%03d" % product.code.to_s %></td>
              <td class="mdl-data-table__cell--non-numeric"><%= product.name %></td>
              <td class="mdl-data-table__cell--non-numeric"><%= number_to_currency product.price, unit: '‎€' %></td>
              <td class="mdl-data-table__cell">
                <%= link_to '', method: :put, class: 'checkout__select_product_button mdl-button mdl-js-button mdl-button--fab mdl-button--mini-fab', product_id: "#{product.id}" do %>
                  <i class="material-icons">add</i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="checkout_products_list mdl-card mdl-cell--4-col">
      <h3 class="mdl-layout__title centered-content">Selected</h3>
      <table class="mdl-data-table mdl-js-data-table" id="products_table">
        <thead>
          <tr>
            <th class="mdl-data-table__cell--non-numeric">Code</th>
            <th class="mdl-data-table__cell--non-numeric">Name</th>
            <th class="mdl-data-table__cell--non-numeric">Price</th>
            <th class="mdl-data-table__cell--non-numeric"></th>
          </tr>
        </thead>
        <tbody>
          <% checkout.products.each do |product| %>
            <tr id=<%= "selected_product_#{product.id}"%>>
              <td class="mdl-data-table__cell--non-numeric"><%= "%03d" % product.code.to_s %></td>
              <td class="mdl-data-table__cell--non-numeric"><%= product.name %></td>
              <td class="mdl-data-table__cell--non-numeric"><%= number_to_currency product.price, unit: '‎€' %></td>
              <td class="mdl-data-table__cell">
                <%= hidden_field_tag "product_ids[]", product.id %>

                <%= link_to '', method: :put, class: 'checkout__unselect_product_button mdl-button mdl-js-button mdl-button--fab mdl-button--mini-fab', for: "selected_product_#{product.id}" do %>
                  <i class="material-icons">remove</i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div id="toast" class="mdl-js-snackbar mdl-snackbar">
    <div class="mdl-snackbar__text"></div>
    <button class="mdl-snackbar__action" type="button"></button>
  </div>
<% end %>

app/views/layouts/_drawer.html.erb
<div class="drawer mdl-layout__drawer">
  <div class="mdl-layout-title">
    <span class="drawer__title">Supermarket</span>
  </div>
  <nav class="mdl-navigation">
    <%= link_to "Products", products_path, class: 'mdl-navigation__link' %>
    <%= link_to "Checkout", checkout_path, class: 'mdl-navigation__link' %>
  </nav>
</div>

app/views/layouts/_header.html.erb
<header class="admin-header mdl-layout__header mdl-layout__header--transparent">
  <div class="mdl-layout__header-row">
    <!-- Title -->
    <span class="admin-header__title mdl-layout-title">Supermarket</span>
  </div>
</header>

<%= render 'layouts/drawer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Supermarket</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <%= render 'layouts/header' %>

      <main class="mdl-layout__content">
        <%= yield %>
      </main>
    </div>

    <!-- JS behaviours -->
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/products/index.html.erb
<div class="mdl-layout__content mdl-grid">
  <div class="mdl-layout-spacer"></div>

  <div class="mdl-cell--8-col">
    <div class="mdl-grid">
      <div class="mdl-layout-spacer"></div>

      <%= link_to new_product_path, class: 'new-record-button mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored' do %>
        <i class="material-icons">add</i>
      <% end %>

      <div class="mdl-card mdl-shadow--2dp mdl-cell--12-col">
        <table class="mdl-data-table mdl-js-data-table" id="products_table">
          <thead>
            <tr>
              <th class="mdl-data-table__cell--non-numeric">Code</th>
              <th class="mdl-data-table__cell--non-numeric">Name</th>
              <th class="mdl-data-table__cell--non-numeric">Price</th>
              <th class="mdl-data-table__cell--non-numeric"></th>
            </tr>
          </thead>
          <tbody>
            <% @products.each do |product| %>
              <tr>
                <td class="mdl-data-table__cell--non-numeric"><%= "%03d" % product.code.to_s %></td>
                <td class="mdl-data-table__cell--non-numeric"><%= product.name %></td>
                <td class="mdl-data-table__cell--non-numeric"><%= number_to_currency product.price, unit: '‎€' %></td>
                <td class="mdl-data-table__cell">
                  <%= link_to product_path(product), method: :delete, class: 'mdl-button mdl-js-button mdl-button--fab mdl-button--mini-fab' do %>
                    <i class="material-icons">remove</i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="mdl-layout-spacer"></div>
</div>

app/views/products/new.html.erb
<div class="mdl-layout__content mdl-grid">
  <div class="mdl-layout-spacer"></div>
  <div class="mdl-card mdl-shadow--2dp mdl-cell--6-col">
    <%= form_for @product, html: { class: 'form' } do |form| %>
      <fieldset>
        <legend>New product</legend>
        <%= form.hidden_field :code, value: form.object.code %>
        
        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
          <%= form.text_field :name, class: 'mdl-textfield__input', id: 'name_field' %>
          <label class="mdl-textfield__label" for="name_field">Name...</label>
        </div>

        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
          <%= form.number_field :price, class: 'mdl-textfield__input', id: 'price_field' %>
          <label class="mdl-textfield__label" for="price_field">Price...</label>
        </div>
      </fieldset>

      <%= form.submit "OK", class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent' %>
    <% end %>
  </div>
  <div class="mdl-layout-spacer"></div>
</div>